In [1]:
import pandas as pd
import os
os.chdir("/home/abhisek/Studies/Python program/Data Kaggle/Practice/Data")

In [2]:
df=pd.read_csv("diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
from sklearn.ensemble import RandomForestClassifier

In [4]:
# press shift tab and see the parameters 
rfc=RandomForestClassifier()

In [5]:
from sklearn.ensemble import RandomForestRegressor

In [6]:
# press shift tab to see the parameters 
rfr=RandomForestRegressor()

In [7]:
import warnings
warnings.filterwarnings("ignore")

In [8]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [9]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

#### in glucose we have some values like zero so we have to replace that value with median 

In [10]:
import numpy as np
df["Glucose"]=np.where(df["Glucose"]==0,df["Glucose"].median(),df["Glucose"])
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72             35        0  33.6   
1            1     85.0             66             29        0  26.6   
2            8    183.0             64              0        0  23.3   
3            1     89.0             66             23       94  28.1   
4            0    137.0             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [11]:
df["Insulin"]=np.where(df["Insulin"]==0,df["Insulin"].median(),df["Insulin"])
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72             35     30.5  33.6   
1            1     85.0             66             29     30.5  26.6   
2            8    183.0             64              0     30.5  23.3   
3            1     89.0             66             23     94.0  28.1   
4            0    137.0             40             35    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [12]:
df["SkinThickness"]=np.where(df["SkinThickness"]==0,df["SkinThickness"].median(),df["SkinThickness"])
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72           35.0     30.5  33.6   
1            1     85.0             66           29.0     30.5  26.6   
2            8    183.0             64           23.0     30.5  23.3   
3            1     89.0             66           23.0     94.0  28.1   
4            0    137.0             40           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [13]:
X=df.iloc[:,[0,1,2,3,4,5,6,7]]
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72           35.0     30.5  33.6   
1            1     85.0             66           29.0     30.5  26.6   
2            8    183.0             64           23.0     30.5  23.3   
3            1     89.0             66           23.0     94.0  28.1   
4            0    137.0             40           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [14]:
y=df.iloc[:,[8]]
y.head()

Outcome
0        1
1        0
2        1
3        0
4        1

In [15]:
## Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=33)
print(X_train.shape)
print(X_test.shape)

(614, 8)
(154, 8)


In [17]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=10)
rfc.fit(X_train,y_train)

RandomForestClassifier(n_estimators=10)

In [18]:
y_pred=rfc.predict(X_test)

In [19]:
y.value_counts()

Outcome
0          500
1          268
dtype: int64

In [20]:
from sklearn import metrics

In [21]:
print(metrics.confusion_matrix(y_test,y_pred))

[[90  9]
 [28 27]]


In [22]:
print("Accuracy",metrics.accuracy_score(y_test,y_pred))

Accuracy 0.7597402597402597


In [23]:
print(metrics.classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.76      0.91      0.83        99
           1       0.75      0.49      0.59        55

    accuracy                           0.76       154
   macro avg       0.76      0.70      0.71       154
weighted avg       0.76      0.76      0.75       154





The main parameters used by a Random Forest Classifier are:

    criterion = the function used to evaluate the quality of a split.
    max_depth = maximum number of levels allowed in each tree.
    max_features = maximum number of features considered when splitting a node.
    min_samples_leaf = minimum number of samples which can be stored in a tree leaf.
    min_samples_split = minimum number of samples necessary in a node to cause node splitting.
    n_estimators = number of trees in the ensamble.



In [25]:
## Manual hyperparameter tuning 
Model1=RandomForestClassifier(n_estimators=300,criterion="entropy",max_features="sqrt",min_samples_leaf=10,random_state=100)
Model1.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', max_features='sqrt',
                       min_samples_leaf=10, n_estimators=300, random_state=100)

In [26]:
y_pred1=Model1.predict(X_test)

In [27]:
metrics.confusion_matrix(y_test,y_pred1)

array([[87, 12],
       [28, 27]])

In [28]:
metrics.accuracy_score(y_test,y_pred1)

0.7402597402597403

In [29]:
print (metrics.classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.76      0.88      0.81        99
           1       0.69      0.49      0.57        55

    accuracy                           0.74       154
   macro avg       0.72      0.68      0.69       154
weighted avg       0.73      0.74      0.73       154



In [30]:
Model2=RandomForestClassifier(n_estimators=500,criterion="gini",max_features="sqrt",min_samples_leaf=10,random_state=100)
Model2.fit(X_train,y_train)

RandomForestClassifier(max_features='sqrt', min_samples_leaf=10,
                       n_estimators=500, random_state=100)

In [32]:
y_pred1=Model1.predict(X_test)

In [33]:
metrics.confusion_matrix(y_test,y_pred1)

array([[87, 12],
       [28, 27]])

In [34]:
metrics.accuracy_score(y_test,y_pred1)

0.7402597402597403

if we change the parameter then it is not right and it should not be based on mood, there are some technique 
with the help of that change the parameters

# Hyperparameter optimization 

## 1. RandomSearchCV

In [35]:
RandomForestClassifier()

RandomForestClassifier()

In [36]:
from sklearn.model_selection import RandomizedSearchCV
# Number of Trees
n_estimators=[int(x) for x in np.linspace(start=200, stop=2000, num=10)]
# Max features
max_features=["auto", "sqrt", "log2"]
# Max Depth
max_depth=[int(x)for x in np.linspace(start=10,stop=1000,num=10)]
# min sample leaf
min_samples_leaf=[4,6,8]
# min sample split
min_samples_split=[4,5,7,9]
# Creating Random Grid
random_grid={"n_estimators":n_estimators,
           "max_features":max_features,
           "max_depth":max_depth,
           "min_samples_leaf":min_samples_leaf,
           "min_samples_split":min_samples_split,
           "criterion":["entropy","gini"]}
print (random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_leaf': [4, 6, 8], 'min_samples_split': [4, 5, 7, 9], 'criterion': ['entropy', 'gini']}


In [37]:
model2=RandomForestClassifier()
model2_randomcv=RandomizedSearchCV(estimator=model2,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,random_state=100,n_jobs=-1)
model2_randomcv.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   33.5s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  5.6min finished


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [4, 6, 8],
                                        'min_samples_split': [4, 5, 7, 9],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [38]:
model2_randomcv.best_params_

{'n_estimators': 600,
 'min_samples_split': 7,
 'min_samples_leaf': 4,
 'max_features': 'auto',
 'max_depth': 10,
 'criterion': 'gini'}

In [39]:
model2_randomcv.best_estimator_

RandomForestClassifier(max_depth=10, min_samples_leaf=4, min_samples_split=7,
                       n_estimators=600)

In [40]:
model2_best=RandomForestClassifier(n_estimators=600,min_samples_split=7,min_samples_leaf=4,max_features="auto",max_depth=10,criterion="gini")

In [41]:
model2_best.fit(X_train,y_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=4, min_samples_split=7,
                       n_estimators=600)

In [42]:
y_predbest=model2_best.predict(X_test)

In [43]:
metrics.confusion_matrix(y_test,y_predbest)

array([[90,  9],
       [25, 30]])

In [44]:
metrics.accuracy_score(y_test,y_predbest)

0.7792207792207793

In [45]:
print(metrics.classification_report(y_test,y_predbest))

              precision    recall  f1-score   support

           0       0.78      0.91      0.84        99
           1       0.77      0.55      0.64        55

    accuracy                           0.78       154
   macro avg       0.78      0.73      0.74       154
weighted avg       0.78      0.78      0.77       154



## 2. GridSearchCV

In [46]:
model2_randomcv.best_params_

{'n_estimators': 600,
 'min_samples_split': 7,
 'min_samples_leaf': 4,
 'max_features': 'auto',
 'max_depth': 10,
 'criterion': 'gini'}

In [47]:
from sklearn.model_selection import GridSearchCV
n_estimators=[300,400,450,500,550,600,650,700,800]
min_samples_split=[4,5,6,7,8,9]
min_samples_leaf=[3,4,5,6]
max_features=["auto"]
max_depth=[5,10,15,20,25,30]
criterion=["gini"]
best_parm={"n_estimators":n_estimators,
          "min_samples_split":min_samples_split,
          "min_samples_leaf":min_samples_leaf,
          "max_features":max_features,
          "max_depth":max_depth,
          "criterion":criterion}
print(best_parm)

{'n_estimators': [300, 400, 450, 500, 550, 600, 650, 700, 800], 'min_samples_split': [4, 5, 6, 7, 8, 9], 'min_samples_leaf': [3, 4, 5, 6], 'max_features': ['auto'], 'max_depth': [5, 10, 15, 20, 25, 30], 'criterion': ['gini']}


In [48]:
model3=RandomForestClassifier()
model3_gridcv=GridSearchCV(estimator=model3,param_grid=best_parm,cv=10,verbose=2,n_jobs=-1)
model3_gridcv.fit(X_train,y_train)

Fitting 10 folds for each of 1296 candidates, totalling 12960 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   18.6s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done 357 tasks      | elapsed:  3.3min
[Parallel(n_jobs=-1)]: Done 640 tasks      | elapsed:  5.8min
[Parallel(n_jobs=-1)]: Done 1005 tasks      | elapsed:  9.0min
[Parallel(n_jobs=-1)]: Done 1450 tasks      | elapsed: 13.0min
[Parallel(n_jobs=-1)]: Done 1977 tasks      | elapsed: 17.7min
[Parallel(n_jobs=-1)]: Done 2584 tasks      | elapsed: 23.5min
[Parallel(n_jobs=-1)]: Done 3273 tasks      | elapsed: 30.8min
[Parallel(n_jobs=-1)]: Done 4042 tasks      | elapsed: 38.5min
[Parallel(n_jobs=-1)]: Done 4893 tasks      | elapsed: 46.8min
[Parallel(n_jobs=-1)]: Done 5824 tasks      | elapsed: 55.3min
[Parallel(n_jobs=-1)]: Done 6837 tasks      | elapsed: 64.5min
[Parallel(n_jobs=-1)]: Done 7930 tasks      | elapsed: 74.4min
[Parallel(n_jobs=-1)]: Done 9105 tasks      | 

GridSearchCV(cv=10, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini'],
                         'max_depth': [5, 10, 15, 20, 25, 30],
                         'max_features': ['auto'],
                         'min_samples_leaf': [3, 4, 5, 6],
                         'min_samples_split': [4, 5, 6, 7, 8, 9],
                         'n_estimators': [300, 400, 450, 500, 550, 600, 650,
                                          700, 800]},
             verbose=2)

In [49]:
model3_gridcv.best_params_

{'criterion': 'gini',
 'max_depth': 5,
 'max_features': 'auto',
 'min_samples_leaf': 5,
 'min_samples_split': 6,
 'n_estimators': 700}

In [50]:
model3_gridcv.best_estimator_

RandomForestClassifier(max_depth=5, min_samples_leaf=5, min_samples_split=6,
                       n_estimators=700)

In [51]:
model3_gridbest=RandomForestClassifier(n_estimators=700,criterion="gini",
                                       max_depth=5,min_samples_leaf=5,min_samples_split=6,max_features="auto")

In [52]:
model3_gridbest.fit(X_train,y_train)
y_predgrid=model3_gridbest.predict(X_test)

In [53]:
metrics.confusion_matrix(y_test,y_predgrid)

array([[89, 10],
       [27, 28]])

In [54]:
metrics.accuracy_score(y_test,y_predgrid)

0.7597402597402597

In [56]:
print (metrics.classification_report(y_test,y_predgrid))

              precision    recall  f1-score   support

           0       0.77      0.90      0.83        99
           1       0.74      0.51      0.60        55

    accuracy                           0.76       154
   macro avg       0.75      0.70      0.72       154
weighted avg       0.76      0.76      0.75       154

